"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SleepTimer.py']
DATA_FILES = ['pause.scpt','icon.icns', 'icon.png']
OPTIONS = {
    'iconfile': 'icon.icns',
     'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps','wheel']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
